🚧 Update to SDK 26.1.100
🏭 This commit was automatically generated by generate-modules-sdk script.

Fix of this commit will be marked as:
☑️🧘🏾‍♂️🏊‍♀️🛌🏿

Full error log:
Error:  asset 2022-7-25--0-27-16--67acc769-dbe1-4796-9c4e-7c7310c5ca31/main.min.js 155 KiB [emitted] (name: main) 1 related asset
runtime modules 57 bytes 1 module
javascript modules 143 KiB
modules by path ./node_modules/ 120 KiB
modules by path ./node_modules/destroyable/dist/*.js 35.9 KiB 10 modules
modules by path ./node_modules/destroyable/dist/errors/*.js 2.59 KiB 2 modules
2 modules
modules by path ./src/ 22.9 KiB
modules by path ./src/*.tsx 10.9 KiB 3 modules
modules by path ./src/animated/*.tsx 11.7 KiB 3 modules
./src/00-index.ts 269 bytes [built] [code generated]
asset modules 126 bytes
./assets/icons/dashed.png 42 bytes [built] [code generated]
./assets/icons/dotted.png 42 bytes [built] [code generated]
./assets/icons/solid.png 42 bytes [built] [code generated]
./package.json 655 bytes [built] [code generated]

ERROR in C:\Users\me\work\collboard\freehand-plus\src\FreehandPlusTool.tsx
./src/FreehandPlusTool.tsx 69:32-85
[tsl] ERROR in C:\Users\me\work\collboard\freehand-plus\src\FreehandPlusTool.tsx(69,33)
TS2352: Conversion of type 'BehaviorSubject<attribute_value>' to type 'string' may be a mistake because neither type sufficiently overlaps with the other. If this was intentional, convert the expression to 'unknown' first.
@ ./src/00-index.ts 4:0-29

ERROR in C:\Users\me\work\collboard\freehand-plus\src\FreehandPlusTool.tsx
./src/FreehandPlusTool.tsx 70:32-91
[tsl] ERROR in C:\Users\me\work\collboard\freehand-plus\src\FreehandPlusTool.tsx(70,33)
TS2352: Conversion of type 'BehaviorSubject<attribute_value>' to type 'string' may be a mistake because neither type sufficiently overlaps with the other. If this was intentional, convert the expression to 'unknown' first.
@ ./src/00-index.ts 4:0-29

ERROR in C:\Users\me\work\collboard\freehand-plus\src\FreehandPlusTool.tsx
./src/FreehandPlusTool.tsx 71:32-86
[tsl] ERROR in C:\Users\me\work\collboard\freehand-plus\src\FreehandPlusTool.tsx(71,33)
TS2352: Conversion of type 'BehaviorSubject<attribute_value>' to type 'number' may be a mistake because neither type sufficiently overlaps with the other. If this was intentional, convert the expression to 'unknown' first.
@ ./src/00-index.ts 4:0-29

ERROR in C:\Users\me\work\collboard\freehand-plus\src\animated\freehand-animated-tool-module.tsx
./src/animated/freehand-animated-tool-module.tsx 58:32-85
[tsl] ERROR in C:\Users\me\work\collboard\freehand-plus\src\animated\freehand-animated-tool-module.tsx(58,33)
TS2352: Conversion of type 'BehaviorSubject<attribute_value>' to type 'string' may be a mistake because neither type sufficiently overlaps with the other. If this was intentional, convert the expression to 'unknown' first.
@ ./src/00-index.ts 5:0-51

ERROR in C:\Users\me\work\collboard\freehand-plus\src\animated\freehand-animated-tool-module.tsx
./src/animated/freehand-animated-tool-module.tsx 59:32-98
[tsl] ERROR in C:\Users\me\work\collboard\freehand-plus\src\animated\freehand-animated-tool-module.tsx(59,33)
TS2352: Conversion of type 'BehaviorSubject<attribute_value>' to type 'string' may be a mistake because neither type sufficiently overlaps with the other. If this was intentional, convert the expression to 'unknown' first.
@ ./src/00-index.ts 5:0-51

ERROR in C:\Users\me\work\collboard\freehand-plus\src\animated\freehand-animated-tool-module.tsx
./src/animated/freehand-animated-tool-module.tsx 60:32-86
[tsl] ERROR in C:\Users\me\work\collboard\freehand-plus\src\animated\freehand-animated-tool-module.tsx(60,33)
TS2352: Conversion of type 'BehaviorSubject<attribute_value>' to type 'number' may be a mistake because neither type sufficiently overlaps with the other. If this was intentional, convert the expression to 'unknown' first.
@ ./src/00-index.ts 5:0-51

webpack 5.35.1 compiled with 6 errors in 6273 ms

Error:
at DevelopmentCompiler.<anonymous> (C:\Users\me\work\collboard\freehand-plus\node_modules\@collboard\modules-sdk\dist\colldev\services\Compiler\Compiler.js:91:37)
at Generator.next (<anonymous>)
at C:\Users\me\work\collboard\freehand-plus\node_modules\@collboard\modules-sdk\dist\colldev\services\Compiler\Compiler.js:8:71
at new Promise (<anonymous>)
at __awaiter (C:\Users\me\work\collboard\freehand-plus\node_modules\@collboard\modules-sdk\dist\colldev\services\Compiler\Compiler.js:4:12)
at Watching.handler (C:\Users\me\work\collboard\freehand-plus\node_modules\@collboard\modules-sdk\dist\colldev\services\Compiler\Compiler.js:85:72)
at C:\Users\me\work\collboard\freehand-plus\node_modules\webpack\lib\Watching.js:204:9
at Hook.eval [as callAsync] (eval at create (C:\Users\me\work\collboard\freehand-plus\node_modules\webpack\node_modules\tapable\lib\HookCodeFactory.js:33:10), <anonymous>:6:1)
at Hook.CALL_ASYNC_DELEGATE [as _callAsync] (C:\Users\me\work\collboard\freehand-plus\node_modules\webpack\node_modules\tapable\lib\Hook.js:18:14)
at Watching._done (C:\Users\me\work\collboard\freehand-plus\node_modules\webpack\lib\Watching.js:201:28)