🚧 Update to SDK 27.36.0
🏭 This commit was automatically generated by generate-modules-sdk script.

Fix of this commit will be marked as:
🤲🏿🧍🏿‍♀️👨🏿‍🎤🍄

Full error log:
Error:  asset 2022-9-14--22-39-55--07280cbe-3aac-4926-b923-5f6762c26949/main.min.js 186 KiB [emitted] (name: main) 1 related asset
runtime modules 57 bytes 1 module
javascript modules 173 KiB
modules by path ./node_modules/ 150 KiB
modules by path ./node_modules/destroyable/dist/*.js 35.9 KiB 10 modules
modules by path ./node_modules/destroyable/dist/errors/*.js 2.59 KiB 2 modules
2 modules
modules by path ./src/ 22.9 KiB
modules by path ./src/*.tsx 11 KiB 3 modules
modules by path ./src/animated/*.tsx 11.7 KiB 3 modules
./src/00-index.ts 269 bytes [built] [code generated]
asset modules 126 bytes
./assets/icons/dashed.png 42 bytes [built] [code generated]
./assets/icons/dotted.png 42 bytes [built] [code generated]
./assets/icons/solid.png 42 bytes [built] [code generated]
./package.json 654 bytes [built] [code generated]

ERROR in C:\Users\me\work\collboard\freehand-plus\src\FreehandPlusArt.tsx
./src/FreehandPlusArt.tsx 9:13-28
[tsl] ERROR in C:\Users\me\work\collboard\freehand-plus\src\FreehandPlusArt.tsx(9,14)
TS2515: Non-abstract class 'FreehandPlusArt' does not implement inherited abstract member 'bottomRight' from class 'Abstract2dArt'.
@ ./src/FreehandPlusTool.tsx 16:26-54
@ ./src/00-index.ts 4:0-29

ERROR in C:\Users\me\work\collboard\freehand-plus\src\FreehandPlusArt.tsx
./src/FreehandPlusArt.tsx 9:13-28
[tsl] ERROR in C:\Users\me\work\collboard\freehand-plus\src\FreehandPlusArt.tsx(9,14)
TS2515: Non-abstract class 'FreehandPlusArt' does not implement inherited abstract member 'topLeft' from class 'Abstract2dArt'.
@ ./src/FreehandPlusTool.tsx 16:26-54
@ ./src/00-index.ts 4:0-29

ERROR in C:\Users\me\work\collboard\freehand-plus\src\animated\freehand-animated-art-module.tsx
./src/animated/freehand-animated-art-module.tsx 15:13-32
[tsl] ERROR in C:\Users\me\work\collboard\freehand-plus\src\animated\freehand-animated-art-module.tsx(15,14)
TS2515: Non-abstract class 'FreehandAnimatedArt' does not implement inherited abstract member 'bottomRight' from class 'Abstract2dArt'.
@ ./src/animated/freehand-animated-tool-module.tsx 16:39-80
@ ./src/00-index.ts 5:0-51

ERROR in C:\Users\me\work\collboard\freehand-plus\src\animated\freehand-animated-art-module.tsx
./src/animated/freehand-animated-art-module.tsx 15:13-32
[tsl] ERROR in C:\Users\me\work\collboard\freehand-plus\src\animated\freehand-animated-art-module.tsx(15,14)
TS2515: Non-abstract class 'FreehandAnimatedArt' does not implement inherited abstract member 'topLeft' from class 'Abstract2dArt'.
@ ./src/animated/freehand-animated-tool-module.tsx 16:39-80
@ ./src/00-index.ts 5:0-51

webpack 5.35.1 compiled with 4 errors in 7157 ms

Error:
at DevelopmentCompiler.<anonymous> (C:\Users\me\work\collboard\freehand-plus\node_modules\@collboard\modules-sdk\dist\colldev\services\Compiler\Compiler.js:91:37)
at Generator.next (<anonymous>)
at C:\Users\me\work\collboard\freehand-plus\node_modules\@collboard\modules-sdk\dist\colldev\services\Compiler\Compiler.js:8:71
at new Promise (<anonymous>)
at __awaiter (C:\Users\me\work\collboard\freehand-plus\node_modules\@collboard\modules-sdk\dist\colldev\services\Compiler\Compiler.js:4:12)
at Watching.handler (C:\Users\me\work\collboard\freehand-plus\node_modules\@collboard\modules-sdk\dist\colldev\services\Compiler\Compiler.js:85:72)
at C:\Users\me\work\collboard\freehand-plus\node_modules\webpack\lib\Watching.js:204:9
at Hook.eval [as callAsync] (eval at create (C:\Users\me\work\collboard\freehand-plus\node_modules\webpack\node_modules\tapable\lib\HookCodeFactory.js:33:10), <anonymous>:6:1)
at Hook.CALL_ASYNC_DELEGATE [as _callAsync] (C:\Users\me\work\collboard\freehand-plus\node_modules\webpack\node_modules\tapable\lib\Hook.js:18:14)
at Watching._done (C:\Users\me\work\collboard\freehand-plus\node_modules\webpack\lib\Watching.js:201:28)